### ISSUE TITLE
The use of Class CL_XLSX_WORKSHEETPART is not permitted.

### ISSUE THREAD

**Issue by ArneVanH** [mkysoft/xlsxreader#3]
Hi,

Stumbled upon this project via dotabap.org where this is marked as cloud compatible.
However when pulling this into an abap environment on BTP there are a bunch of components used within the class that are not released.

As far as I can tell this is (no longer) cloud compatible.

Kr,
Arne

**Comment by larshp** [comment]
@ArneVanH what specific errors do you get?

also see the tooltip,
![image](https://github.com/mkysoft/xlsxreader/assets/5888506/29d20305-c215-40b7-b566-933245692794)

**Comment by ArneVanH** [comment]
A specific error was title of ticket: The use of Class CL_XLSX_WORKSHEETPART is not permitted.

But indeed, that is not a syntax error, but a whitelisting error.  So I suppose it works as intended.

Thanks

**Comment by larshp** [comment]
I'll be fixing it sometime, follow https://github.com/dotabap/dotabap-list/issues/183
